### ISSUE TITLE
Confusion about Batch Size

### ISSUE THREAD

**Issue by bellytina** [Xianjun-Yang/FewDocAE#2]
Hello,
You design the novel N-Way-D-Doc sampling resulting in variable K shots. But the batch size is a fixed number.
Does it mean that batch size is much bigger than K?
For example, there are 8 samples in the support set, and K is 2, so we get 4 batches?
Any help would be great.

**Comment by Xianjun-Yang** [comment]
I do not think batch size influences K. Please check our codes
