### ISSUE TITLE
Event type for FewDocAE dataset?

### ISSUE THREAD

**Issue by Shirley177** [Xianjun-Yang/FewDocAE#3]
Thanks for your contribution! I have a question why there is no event type for each docunment in the dataset?

Looking forward to your reply!

**Comment by Xianjun-Yang** [comment]
In our paper, we construct the data by assuring the same event type for N-way-D-doc event arguments. So we assume the golden event types are known to make it simpler as we are only focusing on the event argument. But you can find the event type in the original DocEE paper if you need it.

**Comment by Shirley177** [comment]
你好，我已收到你的邮件！

**Comment by Shirley177** [comment]
Thank you for your reply! But I don't know a event type corresponding to the argument type of an article. Is there any way to solve it? Or does DocEE give argument roles for each event type?

**Comment by Xianjun-Yang** [comment]
Yes DocEE provides it.
